language: elixir
elixir:
      - 1.1
otp_release:
      - 17.4

sudo: false # to use faster container based build environment

after_script:
    - mix deps.get --only docs
    - MIX_ENV=docs mix inch.report
